apiVersion: v1
kind: Service
metadata:
  name: app-vue
  labels:
    app: app-vue
spec:
  selector:
    app: app-vue
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
