version: "3.8"

services:
  my_app:
    image: aabounegm/devops_app_python
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}"
    networks:
      - loki
    ports:
      - 5000:5000
  loki:
    image: grafana/loki:2.3.0
    networks:
      - loki
    ports:
      - 3100:3100
  grafana:
    image: grafana/grafana:8.1.3
    networks:
      - loki
    ports:
      - 3000:3000
  promtail:
    image: grafana/promtail:2.3.0
    networks:
      - loki
    ports:
      - 9080:9080
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro

networks:
  loki:
